/**
 * This file is collecting every svg icon and exports it;
 * to have a better user experience when using these icons;
 * if you plan to add any icon svgs of your choice, make sure you add them to this file
 * for easier use;
 */

export { ReactComponent as AchievementsIcon } from './achievements.svg';
export { ReactComponent as AppleIcon } from './apple.svg';
export { ReactComponent as ArticleIcon } from './article.svg';
export { ReactComponent as BankIcon } from './bank.svg';
export { ReactComponent as BellIcon } from './bell.svg';
export { ReactComponent as CalendarActiveIcon } from './calendar-active.svg';
export { ReactComponent as CalendarIcon } from './calendar.svg';
export { ReactComponent as CameraIcon } from './camera.svg';
export { ReactComponent as CheckRawIcon } from './check-raw.svg';
export { ReactComponent as CheckIcon } from './check.svg';
export { ReactComponent as ChevronLeftIcon } from './chevron-left.svg';
export { ReactComponent as ChevronRightIcon } from './chevron-right.svg';
export { ReactComponent as ClipIcon } from './clip.svg';
export { ReactComponent as ClockIcon } from './clock.svg';
export { ReactComponent as ClockActiveIcon } from './clock-active.svg';
export { ReactComponent as CloseIcon } from './close.svg';
export { ReactComponent as CurrencyIcon } from './currency.svg';
export { ReactComponent as DotsIcon } from './dots.svg';
export { ReactComponent as EditAltIcon } from './edit-alt.svg';
export { ReactComponent as EditIcon } from './edit.svg';
export { ReactComponent as EyeOffIcon } from './eye-off.svg';
export { ReactComponent as EyeIcon } from './eye.svg';
export { ReactComponent as FacebookIcon } from './facebook.svg';
export { ReactComponent as FilterActiveIcon } from './filter-active.svg';
export { ReactComponent as FilterIcon } from './filter.svg';
export { ReactComponent as FullScreenIcon } from './full-screen.svg';
export { ReactComponent as GoogleIcon } from './google.svg';
export { ReactComponent as HeartIcon } from './heart.svg';
export { ReactComponent as HomeIcon } from './home.svg';
export { ReactComponent as HubActiveIcon } from './hub-active.svg';
export { ReactComponent as HubIcon } from './hub.svg';
export { ReactComponent as JournalIcon } from './journal.svg';
export { ReactComponent as LogoTextIcon } from './logo-text.svg';
export { ReactComponent as LogoIcon } from './logo.svg';
export { ReactComponent as LogoutIcon } from './logout.svg';
export { ReactComponent as MailIcon } from './mail.svg';
export { ReactComponent as MediaIcon } from './media.svg';
export { ReactComponent as MicrophoneIcon } from './microphone.svg';
export { ReactComponent as MicrosoftIcon } from './microsoft.svg';
export { ReactComponent as NextIcon } from './next.svg';
export { ReactComponent as NoteIcon } from './note.svg';
export { ReactComponent as NotificationsIcon } from './notifications.svg';
export { ReactComponent as PauseIcon } from './pause.svg';
export { ReactComponent as PhoneIcon } from './phone.svg';
export { ReactComponent as PlayIcon } from './play.svg';
export { ReactComponent as PodcastIcon } from './podcast.svg';
export { ReactComponent as PreviousIcon } from './previous.svg';
export { ReactComponent as ShieldIcon } from './shield.svg';
export { ReactComponent as SmallScreenIcon } from './small-screen.svg';
export { ReactComponent as SpeakerIcon } from './speaker.svg';
export { ReactComponent as SupportIcon } from './support.svg';
export { ReactComponent as TrashIcon } from './trash.svg';
export { ReactComponent as TrashAltIcon } from './trash-alt.svg';
export { ReactComponent as UserDismissIcon } from './user-dismiss.svg';
export { ReactComponent as UserIcon } from './user.svg';
export { ReactComponent as UsersIcon } from './users.svg';
export { ReactComponent as VideoActiveIcon } from './video-active.svg';
export { ReactComponent as VideoBackgroundIcon } from './video-background.svg';
export { ReactComponent as VideoIcon } from './video.svg';
export { ReactComponent as WalletIcon } from './wallet.svg';
